# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_boot.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BootDialog(object):
    def setupUi(self, BootDialog):
        BootDialog.setObjectName("BootDialog")
        BootDialog.resize(518, 450)
        self.gridLayout_2 = QtWidgets.QGridLayout(BootDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.BootTextEdit = QtWidgets.QTextEdit(BootDialog)
        self.BootTextEdit.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.BootTextEdit.setObjectName("BootTextEdit")
        self.gridLayout.addWidget(self.BootTextEdit, 1, 0, 1, 1)
        self.BootLabel = QtWidgets.QLabel(BootDialog)
        self.BootLabel.setObjectName("BootLabel")
        self.gridLayout.addWidget(self.BootLabel, 0, 0, 1, 1)
        self.CancelButton = QtWidgets.QPushButton(BootDialog)
        self.CancelButton.setObjectName("CancelButton")
        self.gridLayout.addWidget(self.CancelButton, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(BootDialog)
        self.CancelButton.clicked.connect(BootDialog.CancelButton_clicked) # type: ignore
        self.CancelButton.clicked.connect(BootDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BootDialog)

    def retranslateUi(self, BootDialog):
        _translate = QtCore.QCoreApplication.translate
        BootDialog.setWindowTitle(_translate("BootDialog", "Dialog"))
        self.BootLabel.setText(_translate("BootDialog", "Booting..."))
        self.CancelButton.setText(_translate("BootDialog", "Cancel"))
