# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_restore.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RestoreDialog(object):
    def setupUi(self, RestoreDialog):
        RestoreDialog.setObjectName("RestoreDialog")
        RestoreDialog.resize(518, 450)
        self.gridLayout_2 = QtWidgets.QGridLayout(RestoreDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.RestoreTextEdit = QtWidgets.QTextEdit(RestoreDialog)
        self.RestoreTextEdit.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.RestoreTextEdit.setObjectName("RestoreTextEdit")
        self.gridLayout.addWidget(self.RestoreTextEdit, 1, 0, 1, 1)
        self.RestoreLabel = QtWidgets.QLabel(RestoreDialog)
        self.RestoreLabel.setObjectName("RestoreLabel")
        self.gridLayout.addWidget(self.RestoreLabel, 0, 0, 1, 1)
        self.CancelButton = QtWidgets.QPushButton(RestoreDialog)
        self.CancelButton.setObjectName("CancelButton")
        self.gridLayout.addWidget(self.CancelButton, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(RestoreDialog)
        self.CancelButton.clicked.connect(RestoreDialog.CancelButton_clicked) # type: ignore
        self.CancelButton.clicked.connect(RestoreDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(RestoreDialog)

    def retranslateUi(self, RestoreDialog):
        _translate = QtCore.QCoreApplication.translate
        RestoreDialog.setWindowTitle(_translate("RestoreDialog", "Dialog"))
        self.RestoreLabel.setText(_translate("RestoreDialog", "Restoring..."))
        self.CancelButton.setText(_translate("RestoreDialog", "Cancel"))
